networks:
  zamenenet:
    driver: bridge 

services:
  # mssql docker
    zamene-sql:
        container_name: zamene-sql
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: unless-stopped
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=${SQL_PASSWORD}
          - MSSQL_PID=Developer
        ports:
          - ${SQL_PORT}:1433
        expose:
          - 1433
        networks:
          - zamenenet

    zamene-api:
        restart: unless-stopped
        build:
          context: .
        environment:
          - ConnectionStrings:DefaultConnection=Server=${SQL_HOST}, 1433;Database=${SQL_DATABASE};User Id=${SQL_USER};Password=${SQL_PASSWORD};TrustServerCertificate=True
          - ASPNETCORE_ENVIRONMENT=Development
          - RabbitMQ_Host=zamene-rabitmq
          - RabbitMQ_Username=${RABBITMQ_USER} 
          - RabbitMQ_Password=${RABBITMQ_PASSWORD} 
          - RabbitMQ_Virtualhost=/
          - RABBITMQ_PORT=5672
        ports:
          - 5283:5283
        networks:
          - zamenenet
        links:
          - zamene-sql
        depends_on:
          - zamene-sql
          
    #RABBIT_MQ
    zamene-rabitmq:
        image: rabbitmq:3.8-management-alpine
        container_name: zamene
        hostname: zamene
        restart: unless-stopped
        ports:
          - 5672:5672  
          - 15692:15692
        expose:
          - 5672
          - 8080
        environment:
          - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER} 
          - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD} 
        depends_on:
          - zamene-api
        networks:
          - zamenenet
        volumes:
          - ./docker_data/rabbitmq_data:/var/lib/rabbitmq
          - ./docker_data/rabbitmq_logs:/var/log/rabbitmq
        healthcheck:
          test: ["CMD", "rabbitmqctl", "status"]
          interval: 30s
          timeout: 10s
          retries: 5
          
    zamene-mailservice:
        restart: unless-stopped
        container_name: zamene-mailservice
        hostname: zamene-mailservice
        image: registration-email-consumer:latest
        build: 
            context: .
            dockerfile: RegistrationEmailConsumerDockerFile
        environment:
          - RabbitMQ_Host=zamene-rabitmq
          - RabbitMQ_Username=${RABBITMQ_USER} 
          - RabbitMQ_Password=${RABBITMQ_PASSWORD} 
          - RabbitMQ_Virtualhost=/
          - RABBITMQ_PORT=5672
          - Email=${EMAIL_FROM}
          - EmailUsername=${SMTP_USER}
          - Password=${SMTP_PASSWORD}
          - Port=${SMTP_PORT} 
          - Host=${SMTP_HOST}
        # volumes:
        #     - ./appsettings.json:/app/appsettings.json
        depends_on:
               zamene-rabitmq:
                condition: service_healthy
        networks:
           - zamenenet